Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `otm:::generate_dataset()`:
! beta_t_tx != 0 is not TRUE
Backtrace:
     ▆
  1. ├─purrr::list_rbind(purrr::map(1:ITER, ~run_sim(), .progress = TRUE))
  2. │ └─purrr:::check_list_of_data_frames(x)
  3. │   └─vctrs::vec_check_list(x, call = error_call)
  4. │     └─vctrs::obj_check_list(x, ..., arg = arg, call = call)
  5. ├─purrr::map(1:ITER, ~run_sim(), .progress = TRUE)
  6. │ └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  7. │   ├─purrr:::with_indexed_errors(...)
  8. │   │ └─base::withCallingHandlers(...)
  9. │   ├─purrr:::call_with_cleanup(...)
 10. │   └─global .f(.x[[i]], ...)
 11. │     └─global run_sim()
 12. │       └─otm:::generate_dataset(...)
 13. │         └─base::stopifnot(beta_t_tx != 0)
 14. │           └─base::stop(simpleError(msg, call = if (p <- sys.parent(1L)) sys.call(p)))
 15. └─purrr (local) `<fn>`(`<smplErrr>`)
 16.   └─cli::cli_abort(...)
 17.     └─rlang::abort(...)
Execution halted
Script executed in .00333333333333333333 hours.
